config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
root 'static_pages#home'
 get 'static_pages/about'
 
 devise_for :users, :controllers => { registrations: 'registrations' }
 resources :users do
     resource :quick_notes do
         resources :notes
     end
     resource :diary,only: [:show] do
         resources :notes
     end
     resource :publish_notes do
         resources :notes do
             resources :comments,only: [:create]
         end
     end
     resource :shared_notes do
        resources :notes do
            resources :comments, only: [:create]
        end
     end
 end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def about

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="card-group">
  <div class="card">
          <img class="card-img-top" src="..." alt="Card image cap">
              <div class="card-block">
                        <h4 class="card-title">Card title</h4>
                              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                                        </div>
                                          </div>
                                            <div class="card">
                                                    <img class="card-img-top" src="..." alt="Card image cap">
                                                        <div class="card-block">
                                                                  <h4 class="card-title">Card title</h4>
                                                                        <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                                                                              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                                                                                  </div>
                                                                                    </div>
                                                                                      <div class="card">
                                                                                              <img class="card-img-top" src="..." alt="Card image cap">
                                                                                                  <div class="card-block">
                                                                                                            <h4 class="card-title">Card title</h4>
                                                                                                                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
                                                                                                                        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                                                                                                                            </div>
                                                                                                                              </div>
                                                                                                                              </div>

app/views/static_pages/home.html.erb
<section id="cover">
    <div id="cover-caption">
        <div class="container">
            <div class="col-sm-10 col-sm-offset-1"></div>
            <h1 class="display-2">Welcome To The Notebook.</h1>
            <p>This is a notebook app where you can save,share and create discussions on some of your thoughts. Or someone else's for that instance.</p>

            <% unless user_signed_in?%>
                <%= form_for(resource,as: resource_name, url: session_path(resource_name), :html => { class:"form-inline" }) do |f|%>
                    <div class="form-group">
                        <label class="sr-only">Name</label>
                        &emsp;&emsp;&emsp;
                        &emsp;&emsp;&emsp;
                        &emsp;&emsp;&emsp;
                        <%= f.email_field :email , class:"form-control form-control-lg", placeholder:"abc@example.com"%>
                    </div>
                    <div class="form-group">
                        <label class="sr-only">Password</label>

                        <%= f.password_field :password , class:"form-control form-control-lg", placeholder:"Password"%>
                    </div>
                    <%= f.submit "Sign In!", class:"btn btn-success btn-lg"%>
                    </form>
                <%end%>
                </br>
                </br>
                <%= button_to "Sign Up", new_user_registration_path , method: "get", class:"btn btn-success btn-lg"%>
                <br>
                <a href="#page-main" class="btn btn-secondary-outline btn-sm" role="button">&darr;</a>
            <%else%>
                <%= link_to "Sign Out", destroy_user_session_path, class: "btn btn-danger btn-lg", method: :delete%>
            <%end%>



        </div>
    </div>
</section>
<section id="features-of-nbk">
    <div class="section-content">
        <div class-"container">
            <h2>Features of the Notebook</h2>

            <div class="row">
                <div class="col-sm-12">
                    <div class="card-group">
                        <div class="card">
                            <div class="card-block">
                                <h4 class="card-title">Share your notes</h4>
                                <h6 class="card-subtitle">Send to anyone </h6>
                            </div>

                            <%=image_tag("notepass.png")%>
                            <div class="card-block">
                                <p class="card-text">In the notebook, you can send your notes to any user on the app and can receive notes from anyone.Just by your username.</p>
                                <% if user_signed_in? %>
                                    <%= link_to "Go!", user_shared_notes_path(current_user), class: "btn btn-danger"%>
                            <%end%>

                            </div>

                        </div>
                        <div class="card">
                            <div class="card-block">
                                <h4 class="card-title">Publish your notes</h4>
                                <h6 class="card-subtitle">Let everyone know your thoughts </h6>
                            </div>
                            <%=image_tag("bulettin.jpg")%>
                            <div class="card-block">
                                <p class="card-text">In the notebook, you can publish your notes and everyone can see and comment on them. Let your ideas flow!</p>
                                <% if user_signed_in? %>
                                    <%= link_to "Go!", user_diary_path(current_user), class: "btn btn-danger"%>
                                <%end%>
                            </div>

                        </div>
                        <div class="card">
                            <div class="card-block">
                                <h4 class="card-title">Maintain your diary</h4>
                                <h6 class="card-subtitle">Send to anyone </h6>
                            </div>
                            <%= image_tag("diary.jpg")%>
                            <div class="card-block">
                                <p class="card-text">In the notebook, you can maintain your very own personal diary. The notes in the diary will be visible to none. And it will be maintained only for the days you write it.</p>
                                <% if user_signed_in? %>
                                <%= link_to "Go!", user_diary_path(current_user), class: "btn btn-danger"%>
                            <%end%>
                            </div>

                        </div>


                    </div>

                </div>
            </div>

        </div>
    </div>


    </div>

</section>