config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
root 'static_pages#home'
 get 'static_pages/about'
 
 devise_for :users, :controllers => { registrations: 'registrations' }
 resources :users do
     resource :quick_notes do
         resources :notes
     end
     resource :diary,only: [:show] do
         resources :notes
     end
     resource :publish_notes do
         resources :notes do
             resources :comments,only: [:create]
         end
     end
     resource :shared_notes do
        resources :notes do
            resources :comments, only: [:create]
        end
     end
 end

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  scope :quick_notes, -> { where(visibility: 'quick')}
  scope :diary_notes, -> { where(visibility: 'diary')}
  scope :publish_notes, -> { where(visibility: 'publish')}
  scope :sent_notes, -> { where(visibility: 'shared')}
  scope :received_notes, -> { where(visibility: 'shared')}
  default_scope -> { order(created_at: :desc)}
  has_many :comments


  def make_it_quick_note
      update_attribute(:visibility, "quick")
  end

  def make_it_diary_note
      update_attribute(:visibility, "diary")
  end

  def make_it_publish_note
      update_attribute(:visibility, "publish")
  end

  def make_it_shared_note
      update_attribute(:visibility, "shared")
  end

  def creation_date
      created_at.to_date
  end

  def author
      user.to_s
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

    def new
        @note = Note.new
        @user = User.find(params[:user_id])
    end

    def show
        @note = Note.find(params[:id])
        @user = @note.user
        unless on_publish_notes_page || allowed_on_notes_page
            if current_user != @note.user 
                redirect_to root_path
                flash[:notice] = "You are not allowed to do that"
            end
        end
        @comment = Comment.new
    end

    def index
        @user = User.find(params[:user_id])

        unless request.original_fullpath.include?("publish_notes")
            unless request.original_fullpath.include?((current_user.id).to_s)
                redirect_to root_path
                flash[:notice] = "You are not allowed to do that"
            end
        end

        if on_quick_notes_page
            @notes = Note.quick_notes.where(user: @user)
        elsif on_diary_page
            @notes = Note.diary_notes.where(user: @user)
        elsif on_publish_notes_page
            @notes = Note.publish_notes.where(user: @user)
        end
    end

    def create
        @note = current_user.notes.build(note_params) 
        proper_redirection

    end

    def edit
        @note = Note.find(params[:id])
        respond_to do |format|
            format.html
        end
    end

    def update
        @note = Note.find(params[:id])
        if @note.update_attributes(note_params)
            redirect_to user_quick_notes_note_path(current_user,@note)
        end
    end

    def destroy
        @note = Note.find(params[:id])
        @note.delete
        proper_redirection_delete

    end
    private

    def note_params
        params.require(:note).permit(:receiver,:title,:content,:visibility)
    end

    def on_diary_page
        if request.original_fullpath.include?("diary")
            return true
        else
            return false
        end
    end

    def on_quick_notes_page
        if request.original_fullpath.include?("quick")
            return true
        else
            return false
        end
    end

    def on_publish_notes_page
        if request.original_fullpath.include?("publish")
            return true
        else
            return false
        end
    end

    def on_shared_notes_page
        if request.original_fullpath.include?("shared")
            return true
        else
            return false
        end
    end

    def allowed_on_notes_page
        @note = Note.find(params[:id])
        if request.original_fullpath.include?("shared")
            if @note.user == current_user || @note.receiver == current_user.id
                return true
            else
                return false

            end
        end
    end

    def proper_redirection
        if on_quick_notes_page
            @note.make_it_quick_note
            if @note.save
                redirect_to user_quick_notes_path(current_user)
            else
                redirect_to root_path
            end

        elsif on_diary_page
            @note.make_it_diary_note
            if @note.save

                redirect_to user_diary_path(current_user)
            else
                redirect_to root_path
            end
        elsif on_publish_notes_page
            @note.make_it_publish_note
            if @note.save
                redirect_to user_publish_notes_path(current_user)
            else
                redirect_to root_path
            end
        elsif on_shared_notes_page
            @note.make_it_shared_note
            if @note.save
                redirect_to user_shared_notes_path(current_user)
            else
                redirect_to root_path
                flash[:notice] = "Couldn't happen"
            end

        else

            redirect_to root_path
            flash[:alert] = "Couldn't save your note"
        end
    end

    def proper_redirection_delete
        if on_quick_notes_page
            redirect_to user_quick_notes_path(current_user)

        elsif on_diary_page

            redirect_to user_diary_path(current_user)
        end


    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_diary_note.html.erb
<%=form_for([@user,:diary,@note]) do |f|%>
    <div class="col-md-6 form-line">
        <div class="form-group">
            <%=f.label :title%>
            <%=f.text_field :title ,class: "form-control",placeholder: "Title goes here.."%>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%=f.label :content%>
            <%=f.text_area :content, class: "form-control" ,placeholder: "Content goes here.."%>
        </div>
        <div>

            <%=f.submit "Save Note",class: "btn btn-default"%>
        </div>

    </div>

<%end%>
</br>
</br>
</br>
<div style="color: black;">
    This is a diary note. Please note that a diary note can not be altered later. Also, there is a one note per day limit for diary notes.
</div>

app/views/notes/_edit_quick_notes_note.html.erb
<%=form_for([current_user,:quick_notes,@note]) do |f|%>
    <div class="col-md-6 form-line">
        <div class="form-group">
            <%=f.label :title%>
            <%=f.text_field :title ,class: "form-control",placeholder: "Title goes here.."%>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%=f.label :content%>
            <%=f.text_area :content, class: "form-control" ,placeholder: "Content goes here.."%>
        </div>
        <div>

            <%=f.submit "Save Note",class: "btn btn-default"%>
        </div>

    </div>
<%end%>

app/views/notes/_publish_notes_note.html.erb
<%=form_for([@user,:publish_notes,@note]) do |f|%>
    <div class="col-md-6 form-line">
        <div class="form-group">
            <%=f.label :title%>
            <%=f.text_field :title ,class: "form-control",placeholder: "Title goes here.."%>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%=f.label :content%>
            <%=f.text_area :content, class: "form-control" ,placeholder: "Content goes here.."%>
        </div>
        <div>

            <%=f.submit "Save Note",class: "btn btn-default"%>
        </div>

    </div>
<%end%>

<div class="container">
    <div class="row">
        <div class="col md-6 sm-6">

        </div>
    </div>
</div>

app/views/notes/_quick_notes_note.html.erb
<%=form_for([@user,:quick_notes,@note]) do |f|%>
    <div class="col-md-6 form-line">
        <div class="form-group">
            <%=f.label :title%>
            <%=f.text_field :title ,class: "form-control",placeholder: "Title goes here.."%>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%=f.label :content%>
            <%=f.text_area :content, class: "form-control" ,placeholder: "Content goes here.."%>
        </div>
        <div>

            <%=f.submit "Save Note",class: "btn btn-default"%>
        </div>

    </div>
<%end%>

app/views/notes/_shared_notes_note.html.erb
<%=form_for([@user,:shared_notes,@note]) do |f|%>
    <div class="col-md-6 form-line">
        <div class="form-group">
            <%=f.label :title%>
            <%=f.text_field :title ,class: "form-control",placeholder: "Title goes here.."%>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <%=f.label :content%>
            <%=f.text_area :content, class: "form-control" ,placeholder: "Content goes here.."%>
        </div>
        <div>
            <div class="form-group">
                <%= f.label :receiver%>
                <%=f.select :receiver, User.all.collect { |p| [p.name, p.id]} , include_blank: false , class:"btn btn-secondary dropdown-toggle" %>
                </div>

            <%=f.submit "Save Note",class: "btn btn-default"%>
        </div>

    </div>
<%end%>

app/views/notes/edit.html.erb
<section id="contact">
    <div class="section-content">
        <h1 class="section-header">Time to <span class="content-header wow fadeIn " data-wow-delay="0.2s" data-wow-duration="2s"> Write your note</span></h1>
        <h3>Fill in the details below and your note will be created.</h3>
    </div>
    <div class="contact-section">
        <div class="container">
                <%= render 'edit_quick_notes_note'%>
        </div>
</section>

app/views/notes/index.html.erb
<div class="container">
    <div class="jumbotron">
        <p>This is a list of all the notes.</p>
        <p><small>Click on one to see its contents.</small></p>
    </div>
</div>

<section id="shownote">
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <ol class="ordered-list">
                <% @notes.each do |note|%>
                    <% if note.visibility == 'quick'%>
                   <li> <%=link_to note.title, user_quick_notes_note_path(@user,note)%></li>
               <%else%>
                   <li>   <%= link_to note.title, user_publish_notes_note_path(@user,note)%></li>
                <%end%>
            <%end%>
            </ol>
        </div>
    </div>
</div>
</section>

app/views/notes/new.html.erb
<section id="contact">
    <div class="section-content">
        <h1 class="section-header">Get in <span class="content-header wow fadeIn " data-wow-delay="0.2s" data-wow-duration="2s"> Touch with us</span></h1>
        <h3>Lorem Ipsum is simply dummy text of the printing and typesetting industry</h3>
    </div>
    <div class="contact-section">
        <div class="container">
            <% if current_page?(new_user_diary_note_path(current_user))%>
                <%= render 'diary_note'%>
            <%elsif current_page?(new_user_quick_notes_note_path(current_user))%>
                <%= render 'quick_notes_note'%>
            <%elsif current_page?(new_user_publish_notes_note_path(current_user))%>
                <%= render 'publish_notes_note'%>
            <%elsif current_page?(new_user_shared_notes_note_path(current_user))%>
                <%= render 'shared_notes_note'%>
            <%end%>
        </div>
</section>

app/views/notes/show.html.erb
<center><h1 class="display-1"><%= @note.title%></h1></center>
<p class="lead">Author: <%= @note.user.to_s%></p>
<p class="lead">Dated: <%= @note.creation_date%></p>
<div class="show">
    <font face="courier new"><%=  @note.content%></font>
</div>
<% if is_owner?(current_user)  %>
    <%= link_to "Delete Note", user_quick_notes_note_path(current_user,@note), method: :delete, data: { confirm: "Are you sure?"} , class: "btn btn-danger "%>
    <% unless current_page?(user_diary_note_path(current_user,@note)) || current_page?(user_shared_notes_note_path(current_user,@note))%>
        <%= link_to "Update Note", edit_user_quick_notes_note_path(current_user,@note)  , class: "btn btn-success "%>
    <%end%>
<%end%>

<br>
<br>
<br>
<br>
<% if current_page?(user_publish_notes_note_path(@user,@note))%>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h2 class="page-header">Comments</h2>
                <section class="comment-list">
                    <% if @note.comments.any?%>
                        <% @note.comments.each do |comment| %>
                            <article class="row">
                                <div class="col-md-2 col-sm-2 hidden-xs">
                                    <figure class="thumbnail">
                                        <%= image_tag comment.user.avatar.url(:medium)%>
                                        <figcaption class="text-center"><%= comment.user.username%></figcaption>
                                    </figure>
                                </div>
                                <div class="col-md-10 col-sm-10">
                                    <div class="panel panel-default arrow left">
                                        <div class="panel-body">
                                            <header class="text-left">
                                                <div class="comment-user"><i class="fa fa-user"></i><%= comment.user%></div>
                                                <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> <%= comment.created_at.to_date%></time>
                                            </header>
                                            <div class="comment-post">
                                                <p><%= comment.content%></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        <%end%>
                    <%end%>
                    <div class="container">
                        <div class="row">
                            <div class="col md-6 sm-6">

                                <%= form_for([@user,:publish_notes,@note,@comment]) do |f|%>
                                    <div class="from-group">
                                        <%= f.label :comment%>
                                        <%= f.text_area :content, class: "form-control", placeholder: "Write a comment.."%>
                                    </div>
                                    <div>
                                        <%=f.submit "Add comment", class: "btn btn-success"%>
                                    </div>
                                <%end%>
                            </div>
                        </div>
                    </div>

                <%end%>

app/views/notes/update.html.erb
Hello