config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
root 'static_pages#home'
 get 'static_pages/about'
 
 devise_for :users, :controllers => { registrations: 'registrations' }
 resources :users do
     resource :quick_notes do
         resources :notes
     end
     resource :diary,only: [:show] do
         resources :notes
     end
     resource :publish_notes do
         resources :notes do
             resources :comments,only: [:create]
         end
     end
     resource :shared_notes do
        resources :notes do
            resources :comments, only: [:create]
        end
     end
 end

end

app/models/diary.rb
class Diary < ActiveRecord::Base
  belongs_to :user
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
    def show
        @user = User.find(params[:user_id])
        unless is_owner?(current_user)
            flash[:notice] = "You are not allowed that!"
            redirect_to root_path
        end 
        @today = Date.today
        @note = Note.diary_notes.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day,user: @user).first || NullNote.new
        @notes = Note.diary_notes.where(user: @user) || NullNote.new
        @notes_no = @notes.count
    end

    def new

    end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/show.html.erb
<div class="container">

    <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-12 col-md-9">
            <p class="float-right hidden-md-up">
            <button type="button" class="btn btn-primary btn-sm" data-toggle="offcanvas">Toggle nav</button>
            </p>
            <div class="jumbotron"> 
                <h1>Dear Diary,</h1>
                <% if @note.respond_to?("kv")%>
                    <%=link_to "New Note", new_user_diary_note_path(current_user),class:"btn btn-success"%></p>
                <%else%>
                    You have written today's note. Check it out from the table.
                <%end%>
            </div>
            <div class="row">
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div><!--/span-->
            </div><!--/row-->
        </div><!--/span-->

        <div class="col-6 col-md-3 sidebar-offcanvas" id="sidebar">
            <div class="list-group">
                </br>
                <%= link_to @today, @note.respond_to?("kv")? "#" : user_diary_note_path(current_user,@note),class: "list-group-item active" %>
                <% if @notes_no > 0%>
                    <%= link_to @notes.first.created_at.to_date,user_diary_note_path(current_user,@notes.first),class: "list-group-item " %>
                <%end%>
                <% if @notes_no > 1%>

                    <%= link_to @notes.second.created_at.to_date,user_diary_note_path(current_user,@notes.second),class: "list-group-item " %>
                <%end%>
                <% if @notes_no > 2%>
                    <%= link_to @notes.third.created_at.to_date,user_diary_note_path(current_user,@notes.third),class: "list-group-item " %>
                <%end%>
                <% if @notes_no > 3%>

                    <%= link_to @notes.fourth.created_at.to_date,user_diary_notes_path(current_user,@notes.fourth),class: "list-group-item " %>
                <%end%>
                <% if @notes_no > 4%>
                    <%= link_to @notes.fifth.created_at.to_date,user_diary_note_path(current_user,@notes.fifth),class: "list-group-item " %>
                <%end%>
                <%= link_to "Diary","#",class: "list-group-item " %>
            </div>
        </div><!--/span-->
    </div><!--/row-->

    <hr>


</div><!--/.container-->


<!-- Bootstrap core JavaScript