config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
root 'static_pages#home'
 get 'static_pages/about'
 
 devise_for :users, :controllers => { registrations: 'registrations' }
 resources :users do
     resource :quick_notes do
         resources :notes
     end
     resource :diary,only: [:show] do
         resources :notes
     end
     resource :publish_notes do
         resources :notes do
             resources :comments,only: [:create]
         end
     end
     resource :shared_notes do
        resources :notes do
            resources :comments, only: [:create]
        end
     end
 end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true

  has_attached_file :avatar, :styles => {medium: "300x300", small: "150x150" , thumb: "100x100>"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_one :diary
  has_many :notes
  has_many :comments

  def to_s
      name
  end

  def self.search(search)
      where("name LIKE ? or username LIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end

    def index
        if params[:search]
            @users = User.search(params[:search])
        else
            @users = User.all
        end
    end

    def diary
        @user = User.find(params[:id])
        @today = Date.today
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_guest_show.html.erb
<div class="jumbotron">
    <h1 class="display-3"><%= @user.name%>(<%= @user.username%>)</h1>
        <p class="lead"></p>
          <hr class="my-4">
            Doing some stalking?
              <p class="lead"> 

              <center><%= link_to "Published Notes",user_publish_notes_path(@user), class:"btn btn-info btn-lg"%></center>

</div>

<p style="text-align:center;"><%= image_tag @user.avatar.url(:medium), class: "img-cir"%></p>
<

app/views/users/diary.html.erb
<div class="container">

    <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-12 col-md-9">
            <p class="float-right hidden-md-up">
            <button type="button" class="btn btn-primary btn-sm" data-toggle="offcanvas">Toggle nav</button>
            </p>
            <div class="jumbotron"> 
                <h1>Dear Diary,</h1>
                <%=link_to "New Note", new_user_note_path(current_user),class:"btn btn-success"%></p>
            </div>
            <div class="row">
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
                </div><!--/span-->
                <div class="col-6 col-lg-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
                </div><!--/span-->
            </div><!--/row-->
        </div><!--/span-->

        <div class="col-6 col-md-3 sidebar-offcanvas" id="sidebar">
            <div class="list-group">
                </br>
                <%= link_to @today,"#",class: "list-group-item active" %>
                <%= link_to @today-1,"#",class: "list-group-item " %>

                <%= link_to @today-2,"#",class: "list-group-item " %>

                <%= link_to @today-3,"#",class: "list-group-item " %>

                <%= link_to @today-4,"#",class: "list-group-item " %>

                <%= link_to @today-5,"#",class: "list-group-item " %>
            </div>
        </div><!--/span-->
    </div><!--/row-->

    <hr>

    <footer>
        <p>© NOTEBOOK 2017</p>
    </footer>

</div><!--/.container-->


<!-- Bootstrap core JavaScript
    =================

app/views/users/index.html.erb
<h1>This is the list of users on the NOTEBOOK: </h1>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <%= form_tag(users_path, method: :get) do %>
                        <%=text_field_tag :search, params[:search], placeholder: "Search users"%>
                        <%=submit_tag "Search" , class: "btn"%>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
</div>

</br>
<ul class="user_list">
    <% @users.each do |user|%>
        <li> <%= link_to user, user_path(user)%>(<%=user.notes.count%>)</li>
        </br>
    <%end%>
</ul>

app/views/users/show.html.erb
<% if is_owner?(current_user)%>
    <div class="jumbotron">
        <h1 class="display-3"><%= @user.name%>(<%= @user.username%>)</h1>
        <%= link_to "(*settings)", edit_user_registration_path(current_user)%>
        <p class="lead"></p>
        <hr class="my-4">
        <p>What are you upto today?</p>
        <p class="lead"> 
        <%= link_to "Diary", user_diary_path(current_user), class:"btn btn-info btn-lg"%>&emsp; &emsp; &emsp; &emsp; &emsp; &emsp;

        <%= link_to "Publish Notes",user_publish_notes_path(@user), class:"btn btn-info btn-lg"%>&emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
        <%= link_to "Quick Notes",user_quick_notes_path(current_user), class:"btn btn-info btn-lg"%>&emsp; &emsp; &emsp; &emsp; &emsp; &emsp;

        <%= link_to "Shared Notes", user_shared_notes_path(@user), class:"btn btn-info btn-lg"%>&emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
    </div>

    <p style="text-align:center;"><%= image_tag @user.avatar.url(:medium), class: "img-cir"%></p>
<%else%>
    <%= render 'guest_show'%>
<%end%>

"hello  "